version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: pact
        versions: [ ">=2.0.0" ]
    cooldown:
      default-days: 3
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: ruby
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
