version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "07:00"
    ignore:
      - dependency-name: pact
        versions: [ ">=2.0.0" ]
    cooldown:
      default-days: 3
    groups:
      test:
        patterns:
          - "*rspec"
          - "climate_control"
          - "database_cleaner-*"
          - "factory_bot*"
          - "govuk_test"
          - "pact"
          - "rspec-*"
          - "simplecov"
          - "timecop"
          - "webmock"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "07:00"
    ignore:
      - dependency-name: ruby
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "07:00"
    cooldown:
      default-days: 3
