module MongoidInspectionHelpers
  # Object for consuming ActiveSupport::Notifications generated by the moped gem
  # that drives mongoid.
  #
  # The only topic that we are currently interested in is "query.moped", which
  # is triggered on every MongoDB query.
  class MopedQueryCounter < ActiveSupport::LogSubscriber
    cattr_accessor :query_count

    def self.reset
      self.query_count = 0
    end

    # The event handler for "query.moped" notifications.
    def query(_event)
      self.class.query_count += 1
    end
  end

  def mongoid_query_count
    MopedQueryCounter.query_count
  end

  def reset_mongoid_query_count
    MopedQueryCounter.reset
  end
end

RSpec.configure do |config|
  config.include(MongoidInspectionHelpers)

  config.before :suite do
    MongoidInspectionHelpers::MopedQueryCounter.reset
    MongoidInspectionHelpers::MopedQueryCounter.attach_to :moped
  end

  config.before :each do
    reset_mongoid_query_count
  end
end
