default: &default
  adapter: postgresql
  encoding: unicode
  pool: 12
  template: template0

development:
  <<: *default
  database: content_store_development
  url: <%= ENV["DATABASE_URL"]%>

test:
  <<: *default
  database: content_store_test
  url: <%= ENV["TEST_DATABASE_URL"] %>

production:
  <<: *default
  # Rails reads values from DATABASE_URL env var.
