name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - "Jenkinsfile"
      - ".git**"
  pull_request:

jobs:
  security-analysis:
    name: Security Analysis
    uses: alphagov/govuk-infrastructure/.github/workflows/brakeman.yml@main

  lint-ruby:
    name: Lint Ruby
    uses: alphagov/govuk-infrastructure/.github/workflows/rubocop.yml@main

  test-ruby:
    name: Test Ruby
    uses: ./.github/workflows/rspec.yml

  pact-test:
    name: Run Pact tests
    uses: ./.github/workflows/verify-pact.yml
    with:
      # Note: As of January 2023 this relies on Jenkins CI to generate
      # this Pact consumer version. Replatforming does not tag
      # deployed-to-production and the Publishing API CI build doesn't run
      # against the tag when one is created.
      pact-consumer-version: 'branch-deployed-to-production'
